### ISSUE TITLE
Реализовать интерфейс приложения

### ISSUE THREAD

**Issue by Jacbes** [Jacbes/LearningWords#2]
Реализовать интерфейс, меню программы.

**Comment by Jacbes** [comment]
[https://github.com/Jacbes/LearningWords/commit/e28107414a5e26348e5f9f30e30d98432dde3fa4](url)

**Comment by Jacbes** [comment]
Реализован начальный интерфейс.
565de6551b347e5316dee9a666bfa068a0d1e230

**Comment by ChtobiUchitsyaNadoBitProfi** [comment]
Конечный интерфейс программы готов.
5ff9a7b86a6bb2d14a819727fe1377a9332931b6
